# TODO: Put Broadcom copyright header

ifeq ($(ANDROID_ENABLE_BCM_OMX_PROTOTYPE),y)

REFSW_PATH :=vendor/broadcom/bcm_platform/brcm_nexus
LOCAL_PATH := $(call my-dir)

ifeq ($(NEXUS_MODE),proxy)
NEXUS_LIB=libnexus
else
ifeq ($(NEXUS_WEBCPU),core1_server)
NEXUS_LIB=libnexus_webcpu
else
NEXUS_LIB=libnexus_client
endif
endif

include ${REFSW_BASE_DIR}/nexus/lib/playback_ip/b_playback_ip_lib.inc

COMMON_INCLUDE_FILES =  $(TOP)/frameworks/native/include/media/openmax \
                        $(TOP)/frameworks/native/include/utils \
                        $(TOP)/frameworks/native/include/media/hardware  \
                        $(TOP)/frameworks/native/include/ui  \
                        $(TOP)/hardware/libhardware/include/hardware \
                        $(TOP)/vendor/broadcom/bcm_platform/omx_core/inc \
                        $(TOP)/vendor/broadcom/bcm_platform/utils/include \
                        $(TOP)/vendor/broadcom/bcm_platform/brcm_nexus/bin/include \
                        $(TOP)/vendor/broadcom/bcm_platform/libnexusservice \
                        $(TOP)/vendor/broadcom/bcm_platform/libnexusipc \
                        $(TOP)/vendor/broadcom/bcm_platform/libgralloc \
                        $(REFSW_BASE_DIR)/BSEAV/lib/security/common_crypto/include \

COMMON_INCLUDE_FILES += ${NXCLIENT_INCLUDES}

COMMON_SHARED_LIBRARIES=    libc \
                            libutils\
                            liblog \
                            libcutils \
                            $(NEXUS_LIB) \
                            libnexusipcclient \
                            libbcm_utils \
                            libui

COMMON_SOURCE_FILE= src/omx_video.cpp 

ifneq ($(ANDROID_SUPPORTS_NXCLIENT),y)
COMMON_SHARED_LIBRARIES += libnexusservice
endif

REMOVE_NEXUS_CFLAGS := -Wstrict-prototypes -march=armv7-a

COMMON_C_FLAGS := $(filter-out $(REMOVE_NEXUS_CFLAGS), $(NEXUS_CFLAGS))
COMMON_C_FLAGS += $(addprefix -I,$(NEXUS_APP_INCLUDE_PATHS))
COMMON_C_FLAGS += $(addprefix -D,$(NEXUS_APP_DEFINES))
COMMON_C_FLAGS += $(addprefix -I,$(B_PLAYBACK_IP_LIB_PUBLIC_INCLUDES))
COMMON_C_FLAGS += -DLOGD=ALOGD -DLOGE=ALOGE -DLOGW=ALOGW -DLOGV=ALOGV -DLOGI=ALOGI
COMMON_C_FLAGS += -Werror
COMMON_C_FLAGS += -DENABLE_BCM_OMX_PROTOTYPE
ifeq ($(OMX_EXTEND_CODECS_SUPPORT),y)
COMMON_C_FLAGS += -DOMX_EXTEND_CODECS_SUPPORT
endif

#
# libOMX.BCM.mpeg2.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingMPEG2
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.mpeg2.decoder
include $(BUILD_SHARED_LIBRARY)

#
# libOMX.BCM.h264.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingAVC
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.h264.decoder
include $(BUILD_SHARED_LIBRARY)

ifeq ($(ANDROID_ENABLE_SECURE_DECODERS),y)
ifeq ($(SAGE_SUPPORT),y)
#
# libOMX.BCM.h264.DECODER.SECURE
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_C_INCLUDES+=$(REFSW_BASE_DIR)/BSEAV/lib/security/sage/srai/include
LOCAL_C_INCLUDES+=$(REFSW_BASE_DIR)/magnum/syslib/sagelib/include
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_SHARED_LIBRARIES+=libsrai
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingAVC -DENABLE_SECURE_DECODERS
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.h264.decoder.secure
include $(BUILD_SHARED_LIBRARY)
endif
endif

# 
# libOMX.BCM.h263.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingH263
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.h263.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.h265.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingHEVC
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.h265.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.mpeg4.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingMPEG4
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.mpeg4.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.vpx.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingVP8
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.vpx.decoder
include $(BUILD_SHARED_LIBRARY)

ifeq ($(OMX_EXTEND_CODECS_SUPPORT),y)
 
# 
# libOMX.BCM.wmv.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingWMV
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.wmv.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.vc1.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingVC1
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.vc1.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.spark.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingSPARK
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.spark.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.rv.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingRV
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.rv.decoder
include $(BUILD_SHARED_LIBRARY)

# 
# libOMX.BCM.divx.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingDIVX311
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.divx.decoder
include $(BUILD_SHARED_LIBRARY)


# 
# libOMX.BCM.mjpeg.DECODER
#
include $(CLEAR_VARS)
LOCAL_C_INCLUDES+=$(COMMON_INCLUDE_FILES)
LOCAL_SHARED_LIBRARIES:=$(COMMON_SHARED_LIBRARIES)
LOCAL_CFLAGS := $(COMMON_C_FLAGS)
LOCAL_CFLAGS += -DOMX_COMPRESSION_FORMAT=OMX_VIDEO_CodingMJPEG
LOCAL_MODULE_TAGS:= optional
LOCAL_SRC_FILES:= $(COMMON_SOURCE_FILE)
LOCAL_MODULE:=libOMX.BCM.mjpeg.decoder
include $(BUILD_SHARED_LIBRARY)

endif

endif
