/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_broadcom_NdkSample_MyJni */

#ifndef _Included_com_broadcom_NdkSample_MyJni
#define _Included_com_broadcom_NdkSample_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_broadcom_NdkSample_MyJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_broadcom_NdkSample_MyJni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_broadcom_NdkSample_MyJni
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_broadcom_NdkSample_MyJni_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
