LOCAL_PATH := $(DTVKIT_OUTPUT_DIR)

include $(CLEAR_VARS)
LOCAL_MODULE := libdtvkitdvbcore
LOCAL_SRC_FILES := bin/libdvbcore.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdtvkitdvb_hw
LOCAL_SRC_FILES := debug_libs/libdvb_hw.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdtvkitdvb_os
LOCAL_SRC_FILES := debug_libs/libdvb_os.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libdtvkitdvb_version
LOCAL_SRC_FILES := debug_libs/libdvb_version.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_STRIP_MODULE := false
include $(BUILD_PREBUILT)
