LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

ifneq (${LOCAL_DEVICE_RRO_OVERLAY},)

LOCAL_CERTIFICATE := platform
LOCAL_SDK_VERSION := current
LOCAL_RESOURCE_DIR := $(LOCAL_DEVICE_RRO_OVERLAY)
LOCAL_PACKAGE_NAME := BcmFwksDevRro

include $(BUILD_RRO_PACKAGE)

endif
