/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_bcmnativeplayer_native_BcmNativePlayer */

#ifndef _Included_com_android_bcmnativeplayer_native_BcmNativePlayer
#define _Included_com_android_bcmnativeplayer_native_BcmNativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_bcmnativeplayer_native_BcmNativePlayer
 * Method:    start
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_bcmnativeplayer_native_1BcmNativePlayer_start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_android_bcmnativeplayer_native_BcmNativePlayer
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_bcmnativeplayer_native_1BcmNativePlayer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
