/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_broadcom_tvinput_TunerHAL */

#ifndef _Included_com_broadcom_tvinput_TunerHAL
#define _Included_com_broadcom_tvinput_TunerHAL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_broadcom_tvinput_TunerHAL
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_broadcom_tvinput_TunerHAL_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_broadcom_tvinput_TunerHAL
 * Method:    tune
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_broadcom_tvinput_TunerHAL_tune
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_broadcom_tvinput_TunerHAL
 * Method:    getChannelList
 * Signature: ()[Lcom/broadcom/tvinput/ChannelInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_broadcom_tvinput_TunerHAL_getChannelList
  (JNIEnv *, jclass);

/*
 * Class:     com_broadcom_tvinput_TunerHAL
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_broadcom_tvinput_TunerHAL_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
