LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_CERTIFICATE := platform
LOCAL_SDK_VERSION := current
LOCAL_RESOURCE_DIR := $(LOCAL_PATH)/res
ifneq (${LOCAL_DEVICE_RRO_OVERLAY},)
#LOCAL_RESOURCE_DIR += $(LOCAL_DEVICE_RRO_OVERLAY)
endif
LOCAL_PACKAGE_NAME := BcmFwksRro

include $(BUILD_RRO_PACKAGE)
